---
repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
# FIXME: doesn't work properly on NTFS managed shares.
#      - id: check-executables-have-shebangs

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    - id: forbid-binary
    - id: rubocop
      args: [--fix-layout]
# FIXME: doesn't work properly on NTFS managed shares.
#    - id: script-must-have-extension
#    - id: script-must-not-have-extension
    - id: shellcheck
      additional_dependencies: []
